### ISSUE TITLE
Could not load postgis extension for postgresql

### ISSUE THREAD

**Issue by LVladymyr** [vpicavet/docker-3dgis#4]
Hi @vpicavet. I could not load postgis extension for postgresql with this image

Step to reproduse:
1. create user and db

``` bash
$createuser --no-superuser --no-createrole --createdb osm
$createdb -E UTF8 -O osm osm
```
1. create postgis extension for it:

``` bash
$echo "CREATE EXTENSION postgis;" |psql -d osm
```

3 It has failed with message:

``````
ERROR:  could not load library "/usr/lib/postgresql/9.5/lib/postgis-2.2.so": libboost_thread.so.1.54.0: cannot open shared object file: No such file or directory```
But file exists and has inough permmision  to read and execute. 
``````

**Comment by vpicavet** [comment]
Hi,

What docker commands did you run before first step ? Are you sure to be inside the container when you use createuser ?

**Comment by LVladymyr** [comment]
Yep, it was inside docker container.
I have changed docker image for my project. So this issue is not important for me.

**Comment by vpicavet** [comment]
ok, someone reopen if the problem reappears elsewhere.
